Added the Helm chart for the Secrets Manager operator (#123)
* Added the Helm chart for the Secrets Manager operator

* Some formatting changes requested by GitHub

* Adding end-of-file carriage return suggested by GitHub

* Removing the schema definition from the schema itself to match what we have in the other chart

* Fixing an issue with the identity URL override

* README and CRD description updates.

* Updating to use GHCR

* Adding optional image pull secrets

* Adding missing properties to the values schema

* Adding sm-operator to the build.  Differentiating the versioning workflows for multiple charts.

* Fixing sed statement for appVersion lookup

* Adding the operator README to the root readme.  Updating the .helmignore to include any test files and the README

* Adding Dev Container for testing purposes.

* Locking down affinity to only the architectures we currently support.  These are the only ones we have static binaries for.

* First attempt to allow tests with the Helm chart

* Adding conditional in self-install test

* Adding SM-operator tests

* Testing the auth token secret creation

* Adding workflow to production environment

* Testing secret creation

* Moving the test file to the workflows directory

* Checking logs and adding sleep

* Adding tail so I can see the logs

* Trying without the quotes on the auth secret for now

* Testing auth token length

* Fixing auth token env variable setting

* Adding some further tests

* Adding a small wait

* Fixing inverted logic

* Improving logging layout

* Adding newlines requested by GitHub

* Apply suggestions from code review

Co-authored-by: Vince Grassia <593223+vgrassia@users.noreply.github.com>

* Adding exectue permissions to postCreateCommand.sh

* Including a small testing message around Docker Desktop/DevContainers

* Fixing capitalization in values.yaml

* Manually bumping the version to 0.1.0

* Removing the image pull secret from the test files.

* Fixing linter error for trailing spaces

* Fixing the tag on the test values file

---------

Co-authored-by: Vince Grassia <593223+vgrassia@users.noreply.github.com>

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -16,6 +16,7 @@ jobs:
   test:
     name: Test Helm charts
     runs-on: ubuntu-22.04
+    environment: Production
     steps:
       - name: Checkout repo
         uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
@@ -26,6 +27,18 @@ jobs:
         uses: Azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
         with:
           version: 'v3.13.1'
+
+      - name: Login to Azure - CI Subscription
+        uses: Azure/login@e15b166166a8746d1a47596803bd8c1b595455cf # v1.6.0
+        with:
+          creds: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}
+
+      - name: Retrieve secrets
+        id: retrieve-secrets
+        uses: bitwarden/gh-actions/get-keyvault-secrets@main
+        with:
+          keyvault: "bitwarden-ci"
+          secrets: "helm-sm-operator-ci-test-access-token"
 
       - name: Set up lynx
         run: sudo apt install lynx
@@ -45,6 +58,7 @@ jobs:
           CHANGED=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
           if [[ -n "$CHANGED" ]]; then
             echo "changed=true" >> $GITHUB_OUTPUT
+            echo "changed-list=$CHANGED" >> $GITHUB_OUTPUT
           fi
 
       - name: Create kind cluster
@@ -107,12 +121,17 @@ jobs:
 
           kubectl create secret tls tls-secret --cert=bitwarden.localhost.pem --key=bitwarden.localhost.key
 
+          #Setup image pull secret
+          kubectl create secret -n bitwarden docker-registry ghcr-login-secret --docker-server=ghcr.io --docker-username=bitwarden-devops-bot --docker-password=${{ secrets.GITHUB_TOKEN }} --docker-email=106330231+bitwarden-devops-bot@users.noreply.github.com
+
+
+
       - name: Run chart-testing (install)
         if: steps.list-changed.outputs.changed == 'true'
         run: ct install --target-branch ${{ github.event.repository.default_branch }} --skip-clean-up --namespace bitwarden
 
-      - name: Test install
-        if: steps.list-changed.outputs.changed == 'true'
+      - name: Test install (self-host)
+        if: steps.list-changed.outputs.changed == 'true' && contains(steps.list-changed.outputs.changed-list,'self-host')
         run: |
           #For review purposes
           echo "*****DEPLOYMENTS*****"
@@ -174,6 +193,57 @@ jobs:
           fi
 
           echo "Admin OK."
+
+
+      - name: Test install (sm-operator)
+        if: steps.list-changed.outputs.changed == 'true' && contains(steps.list-changed.outputs.changed-list,'sm-operator')
+        run: |
+          #For review purposes
+          echo "*****DEPLOYMENTS*****"
+          kubectl get deployments
+
+          echo "*****PODS*****"
+          pods=$(kubectl get pods -l app.kubernetes.io/name=sm-operator | grep 2/2)
+          echo $pods
+
+          if [[ -z "$pods" ]]; then
+            echo "::error::No pods found."
+            exit 1
+          fi
+
+          echo "*****CREATING AUTH SECRET*****"
+          kubectl create secret generic bw-auth-token -n bitwarden --from-literal=token="$AUTH_TOKEN"
+          echo "*****CREATING BW SECRET*****"
+          kubectl apply -f .github/workflows/config/sample-bw-secret.yaml
+
+          # Sleeping while BitwardenSecret is being created and synced
+          sleep 2s
+
+          echo "*****LOGS*****"
+          logs=$(kubectl logs -l app.kubernetes.io/name=sm-operator -c manager)
+          echo "$logs"
+
+          completed=$(echo "$logs"| grep "Completed sync for bitwarden/bitwardensecret-sample")
+
+          if [[ -z "$completed" ]]; then
+            echo "::error::Secret did not sync."
+            exit 1
+          fi
+
+          echo "*****RESULTING SECRETS*****"
+          secrets=$(kubectl get secrets)
+          echo "$secrets"
+
+          secretCreated=$(echo "$secrets" | grep "bw-sample-secret                               Opaque                           3")
+
+          if [[ -z "$secretCreated" ]]; then
+            echo "::error::Secret not created correctly."
+            exit 1
+          fi
+
+          echo "*****OPERATOR OK*****"
+        env:
+          AUTH_TOKEN: ${{ steps.retrieve-secrets.outputs.helm-sm-operator-ci-test-access-token }}
 
       - name: Clean-up
         if: steps.list-changed.outputs.changed == 'true'
