Adding new test to update version to check if the versions have been pushed to Docker Hub

diff --git a/.github/workflows/update-versions.yml b/.github/workflows/update-versions.yml
--- a/.github/workflows/update-versions.yml
+++ b/.github/workflows/update-versions.yml
@@ -74,6 +74,37 @@ jobs:
           fi
         working-directory: charts/self-host/templates
 
+      - name: Verify if image versions are on Docker Hub
+        id: web-update
+        env:
+          COREVERSION: ${{ steps.get-core.outputs.version }}
+          WEBVERSION: ${{ steps.get-web.outputs.version }}
+        run: |
+          coreimages=( "admin" "api" "attachments" "events" "icons" "identity" "notifications" "scim" "sso" "mssqlmigratorutility" )
+
+          test_image() {
+              image=$1
+              version=$2
+
+              tag=$(curl -s "https://registry.hub.docker.com/v2/repositories/bitwarden/$image/tags/"|jq '."results"[]["name"]' | grep $version)
+              if [[ -z "$tag" ]]; then
+                  echo "$image - $version - NOT FOUND!"
+                  echo "Stopping..."
+                  exit 1
+              else
+                  echo "$image - $tag - FOUND"
+              fi
+          }
+
+          for key in "${!coreimages[@]}"
+          do
+              image=${coreimages[$key]}
+
+              test_image $image $COREVERSION
+          done
+
+          test_image "web" $WEBVERSION
+
   update-versions:
     name: "Update Versions"
     if: |
