Refactor to use semver check, instead of external action

diff --git a/.github/workflows/version-bump-self-host.yml b/.github/workflows/version-bump-self-host.yml
--- a/.github/workflows/version-bump-self-host.yml
+++ b/.github/workflows/version-bump-self-host.yml
@@ -3,8 +3,8 @@ name: Version Bump - Self Host
 on:
   workflow_dispatch:
     inputs:
-      version_number_override:
-        description: "New version override (leave blank for automatic calculation, example: '1.0.1')"
+      version_number:
+        description: "New version (example: '1.0.1')"
         required: true
         type: string
 
@@ -19,9 +19,11 @@ jobs:
       id-token: write
     steps:
       - name: Validate version input
-        uses: bitwarden/gh-actions/version-check@main
-        with:
-          version: ${{ inputs.version_number_override }}
+        run: |
+          if [[ ! "${{ inputs.version_number }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Invalid version format."
+            exit 1
+          fi
 
       - name: Checkout Branch
         uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
@@ -74,10 +76,10 @@ jobs:
           echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
 
       - name: Verify input version
-        if: ${{ inputs.version_number_override != '' }}
+        if: ${{ inputs.version_number != '' }}
         env:
           CURRENT_VERSION: ${{ steps.current-version.outputs.version }}
-          NEW_VERSION: ${{ inputs.version_number_override }}
+          NEW_VERSION: ${{ inputs.version_number }}
         run: |
           # Error if version has not changed.
           if [[ "$NEW_VERSION" == "$CURRENT_VERSION" ]]; then
@@ -99,13 +101,13 @@ jobs:
         uses: bitwarden/gh-actions/version-bump@main
         with:
           file_path: "charts/self-host/Chart.yaml"
-          version: ${{ inputs.version_number_override }}
+          version: ${{ inputs.version_number }}
 
       - name: Set final version output
         id: set-final-version-output
         run: |
           if [[ "${{ steps.bump-version-override.outcome }}" == "success" ]]; then
-            echo "version=${{ inputs.version_number_override }}" >> $GITHUB_OUTPUT
+            echo "version=${{ inputs.version_number }}" >> $GITHUB_OUTPUT
 
       - name: Check if version changed
         id: version-changed
